'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Crowbar.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на http://steamcommunity.com/id/zeqmacaw.
        '''</summary>
        Friend ReadOnly Property About_AuthorLink() As String
            Get
                Return ResourceManager.GetString("About_AuthorLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Goto Steam Group.
        '''</summary>
        Friend ReadOnly Property About_GotoSteamGroupText() As String
            Get
                Return ResourceManager.GetString("About_GotoSteamGroupText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на http://paypal.me/zeqmacaw.
        '''</summary>
        Friend ReadOnly Property About_PayPalLink() As String
            Get
                Return ResourceManager.GetString("About_PayPalLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на GoldSource and Source Engine Modding Toolset:
        '''* Decompiler of MDL and related files.
        '''* Compiler interface to StudioMDL.exe tool.
        '''* Model viewer interface to Half-Life Model Viewer tool.
        '''* Unpacker of Fairy Tale Busters APK, Tactical Intervention FPX, Garry&apos;s Mod GMA, Vampire: The Masquerade - Bloodlines VPK files, and Source-engine VPK files.
        '''* Packer interface to Garry&apos;s Mod GMA and Source-engine VPK packer tools.
        '''* Downloader of Workshop items from any Steam game that allows public downloads.
        '''* Publisher  [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property About_ProductDescription() As String
            Get
                Return ResourceManager.GetString("About_ProductDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на http://steamcommunity.com/groups/CrowbarTool.
        '''</summary>
        Friend ReadOnly Property About_ProductLink() As String
            Get
                Return ResourceManager.GetString("About_ProductLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на https://steamcommunity.com/groups/CrowbarTool/discussions/1/.
        '''</summary>
        Friend ReadOnly Property BugReportLink() As String
            Get
                Return ResourceManager.GetString("BugReportLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на https://steamcommunity.com/groups/CrowbarTool/discussions/1/.
        '''</summary>
        Friend ReadOnly Property BugReportLink1() As String
            Get
                Return ResourceManager.GetString("BugReportLink1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property crowbar_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("crowbar_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;AppSettings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;GameSetups&gt;
        '''    &lt;GameSetup&gt;
        '''      &lt;GameName&gt;Age of Chivalry&lt;/GameName&gt;
        '''      &lt;GameEngine&gt;Source&lt;/GameEngine&gt;
        '''      &lt;GamePathFileName&gt;&amp;lt;library1&amp;gt;\steamapps\common\Source SDK Base 2007\ageofchivalry\gameinfo.txt&lt;/GamePathFileName&gt;
        '''      &lt;GameAppPathFileName&gt;&amp;lt;library1&amp;gt;\steamapps\common\Source SDK Base 2007\hl2.exe&lt;/GameAppPathFileName&gt;
        '''      &lt;Game [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Crowbar_Settings() As String
            Get
                Return ResourceManager.GetString("Crowbar_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-ANI.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugAniFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugAniFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-MDL.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugMdlFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugMdlFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-PHY.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugPhyFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugPhyFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-SequenceGroupMDL.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugSequenceGroupMDLFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugSequenceGroupMDLFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-TextureMDL.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugTextureMDLFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugTextureMDLFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-VTX.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugVtxFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugVtxFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-VVD.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_DebugVvdFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_DebugVvdFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на decompile-log.txt.
        '''</summary>
        Friend ReadOnly Property Decompile_LogFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Decompile_LogFileNameSuffix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Possible causes: The game&apos;s SDK or Authoring Tools has not been installed (usually via Steam Library Tools) or the path given to Crowbar (via Set Up Games button) is incorrect..
        '''</summary>
        Friend ReadOnly Property ErrorMessageSDKMissingCause() As String
            Get
                Return ResourceManager.GetString("ErrorMessageSDKMissingCause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на http://steamcommunity.com/sharedfiles/filedetails/?id=791755353.
        '''</summary>
        Friend ReadOnly Property Help_CrowbarGuideLink() As String
            Get
                Return ResourceManager.GetString("Help_CrowbarGuideLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на https://steamcommunity.com/sharedfiles/workshoplegalagreement.
        '''</summary>
        Friend ReadOnly Property Link_SteamSubscriberAgreement() As String
            Get
                Return ResourceManager.GetString("Link_SteamSubscriberAgreement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на unpack-log.txt.
        '''</summary>
        Friend ReadOnly Property Unpack_LogFileNameSuffix() As String
            Get
                Return ResourceManager.GetString("Unpack_LogFileNameSuffix", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
